"""Добавлен столбец photo_id в таблицу equipment и связи

Revision ID: 060076cb978e
Revises: 
Create Date: 2025-06-15 18:18:23.863584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060076cb978e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_equipment_photo_id', 'photo', ['photo_id'], ['id']) # Имя добавлено!
        batch_op.alter_column('category_id', nullable=False) # Добавлено NOT NULL
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_equipment_photo_id', type_='foreignkey') # Имя добавлено!
        batch_op.drop_column('photo_id')
        batch_op.alter_column('category_id', nullable=True) # Добавлено NULL

    # ### end Alembic commands ###